### ISSUE TITLE
Weitere Validierungen hinzufügen (z.B. Pflichtfeld)

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/yform_dropzone#1]
Die vom Upload-Feld bekannten Validierungen sollen auch mit Dropzone funktionieren, heißt:

- ist Pflichtfeld und ausgefüllt? - In der Umsetzung: gibt es zu dieser Session und zu dieser Tabelle und zu diesem Feld schon ein Verzeichnis mit Dateiinhalten?
- ~Dateigröße min/max pro Datei~
- ~Dateiendung~

Zudem als Idee

- Dateigröße min/max gesamt
- Dateianzahl min/~max (clientseitig umgesetzt)~

**Comment by MC-PMOE** [comment]
Wäre es nicht möglich das über die Validierungs-Klassen von YForm individuell zu lösen (Für Pflichtfeld einfach empty bei Bedarf) oder geht es um die clientseitige Validierung?
Oder muss man dropzone noch anpassen damit die Validierungs-Klassen richtig greifen?

**Comment by alexplusde** [comment]
Es gibt schlichtweg noch keine Validierung in YForm für solche Fälle. Es geht um die serverseitige Validierung.
