### ISSUE TITLE
Doku-Seite schöner machen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/yform_dropzone#20]
Die verliert momentan das Menü von YForm. 

@gharlan hast du mir einen Tipp, wie ich das richtig anlege in der package.yml oder wie kann ich das mit Menü (Addon-Menü oben) rendern?

**Comment by gharlan** [comment]
Hmm, das scheint irgendein spezielles Subpage-Handling in yform zu sein.

Ändere ich `yform/dropzone` hier in der package.yml in `cronjob/dropzone`, wird die Seite im Cronjob-Addon korrekt eingebunden, inkl. Menü.

Schaue es mir nachher mal an, was yform da macht.

Die PHP-Page hier im Addon im pages-Ordner wird übrigens nicht benötigt, die kann weg.
