### ISSUE TITLE
Doku: Sprachcodes-JSON

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/yform_dropzone#21]
```
{
    "add":"Dateien hinzufügen",
    "start":"Upload starten",
    "clear":"zurücksetzen",
    "dictDefaultMessage":"Dateien auf dieses Feld ziehen",
    "dictFallbackMessage":"Ihr Browser untersützt leider keine Drag\'n\'Drop Datei Uploads",
    "dictFallbackText":"",
    "dictFileTooBig":"Datei ist zu groß",
    "dictInvalidFileType":"Dateityp wird nicht unterstützt",
    "dictResponseError":"Ein Fehler ist aufgetreten. Ein oder mehrere Dateien konnten nicht hochgeladen werden.",
    "dictCancelUpload":"abbrechen",
    "dictUploadCanceled":"Upload wurde abgebrochen",
    "dictCancelUploadConfirmation":"Upload wird abgebrochen",
    "dictRemoveFile":"entfernen",
    "dictRemoveFileConfirmation":"Datei wird entfernt",
    "dictMaxFilesExceeded":"Zuviele Dateien",
    "dictFileSizeUnits":"mb"
}
```

muss in die Felddefinition. Könnte man auch direkt bei der Eingabe der Parameter per default einfügen.

**Comment by Geri2017** [comment]
direkt in die https://github.com/FriendsOfREDAXO/yform_dropzone/edit/master/lang/de_de.lang?
z.B: `yform_values_dropzone_add = Dateien hinzufügen` ?

**Comment by alexplusde** [comment]
zum einen sollten sie default-artig aus der de_de.lang gelesen werden - bisher sind sie irgendwo im Code fest verdrahtet. Zum anderen muss der Nutzer sie überschreiben können, also muss man diesen Block oben auch noch mal in die README.md aufnehmen.

**Comment by Geri2017** [comment]
Ist denn der o.a. Ansatz richtig?
`yform_values_dropzone_add = Dateien hinzufügen`

**Comment by alexplusde** [comment]
Ich denke, schon. Aber wie ich gerade feststelle, habe ich das ohnehin so gelöst, dass eine Übersetzung in der de_de nicht nötig ist. Ich fürchte, ich muss das Issue selbst mal bearbeiten.
