### ISSUE TITLE
Warnings 

### ISSUE THREAD

**Issue by Geri2017** [FriendsOfREDAXO/yform_dropzone#24]
Warning: array_merge() [<a href='https://php.net/manual/function.array-merge'>function.array-merge</a>]: Argument #2 is not an array in redaxo/src/addons/yform_dropzone/ytemplates/bootstrap/value.dropzone.tpl.php on line 25

Warning: Invalid argument supplied for foreach() in redaxo/src/addons/yform_dropzone/ytemplates/bootstrap/value.dropzone.tpl.php on line 29

**Comment by alexplusde** [comment]
Das passiert aktuell, wenn kein Wörterbuch vorhanden ist. #21 beachten
