### ISSUE TITLE
Error / kein upload möglich: ErrorCode - InsertQueryError

### ISSUE THREAD

**Issue by Geri2017** [FriendsOfREDAXO/yform_dropzone#25]
Error while executing statement "INSERT INTO `rex_dropzone` SET `dropzone` = :dropzone" using params {"dropzone":null}! SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'dropzone' cannot be null

**Comment by alexplusde** [comment]
Fix ist in Arbeit... Bis dahin manuell im Adminer null erlauben
