### ISSUE TITLE
Frontend Upload Sicherheitslücke?

### ISSUE THREAD

**Issue by rkemmere** [FriendsOfREDAXO/yform_dropzone#33]
Leider bekomme ich es nicht hin, das für jeden Besucher beim hochladen ein eigener Ordner genommen wird .
Wenn ich es mit zwei Nutzern teste, sieht jeder der Nutzer was der andere hochgeladen hat.

Die uniqueId wird irgendwie gar nicht durchgeschleift.

**Comment by alexplusde** [comment]
https://github.com/FriendsOfREDAXO/yform_dropzone#hinweise-und-bekannte-probleme-in-dieser-version

**Comment by alexplusde** [comment]
und https://github.com/FriendsOfREDAXO/yform_dropzone/issues/22

**Comment by alxndr-w** [comment]
Konntest du das Problem noch lösen?

**Comment by rkemmere** [comment]
Ich habe es so gelöst, dass ich die unique ID mit Abfrage.

`
			// Ausgabe bisher hochgeladener Dateien
			$result  = array();
			$uniqueKey = rex_request("uniqueKey", 'string', 'public');
			
			if(file_exists(self::getPath()) && $uniqueKey != "") {
				$files = scandir(self::getPath());
				if ( false !== $files ) {
					foreach ( $files as $file ) {
						if ( '.' != $file && '..' != $file) {
							$obj['name'] = $file;
							$obj['uniqueKey'] = $uniqueKey;
							$obj['size'] = filesize(self::getPath().$file);
							$result[] = $obj;
						}
					}
				}
			 }
			header('Content-type: text/json');
			header('Content-type: application/json');
			exit( json_encode( $result ) );

		}`

**Comment by alxndr-w** [comment]
PR welcome
